### ISSUE TITLE
DependencyPackager fails on linux

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#130]
DependenciesPackager 1.0.1-rc2-15132 fails with this error on Linux.

>  fail: DependenciesPackager.Program[0]
        System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection.
        Parameter name: chunkLength) ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
        Parameter name: chunkLength
           at System.Text.StringBuilder.ToString()
           at DependenciesPackager.CrossgenContext.CrossgenAssembly(PackageEntry package, LibraryAsset asset, String targetPath)
           at DependenciesPackager.CrossgenContext.<>c__DisplayClass19_0.<Crossgen>b__0(PackageEntry package)

**Comment by natemcmaster** [comment]
Not sure why. This appears to be fixed now.
