### ISSUE TITLE
AssemblyHasAttributeRuleBase rule fails while attempting to delete file

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/BuildTools#135]
Changes introduced in https://github.com/aspnet/BuildTools/pull/128

> Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Users\namc\AppData\Local\Temp\tmp98A3.dll' because it is being used by another process.
   at System.IO.Win32FileSystem.DeleteFile(String fullPath)
   at System.IO.File.Delete(String path)
   at NuGetPackageVerifier.Rules.AssemblyHasAttributeRuleBase.Validate(PackageAnalysisContext context)
   at NuGetPackageVerifier.Rules.DefaultCompositeRule.<Validate>d__1.MoveNext()
   at NuGetPackageVerifier.Rules.AdxVerificationCompositeRule.<Validate>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by natemcmaster** [comment]
cc @ajaybhargavb
