### ISSUE TITLE
Reenable AssemblyIsBuiltInReleaseConfigurationRule

### ISSUE THREAD

**Issue by pranavkm** [aspnet/BuildTools#140]
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
  Parameter name: assemblyResolver
     at Mono.Cecil.MetadataResolver..ctor(IAssemblyResolver assemblyResolver)
     at Mono.Cecil.ModuleDefinition.get_MetadataResolver()
     at Mono.Cecil.ModuleDefinition.Resolve(TypeReference type)
     at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
     at Mono.Cecil.SignatureReader.ReadCustomAttributeEnum(TypeReference enum_type)
     at Mono.Cecil.SignatureReader.ReadCustomAttributeElement(TypeReference type)
     at Mono.Cecil.SignatureReader.ReadCustomAttributeConstructorArguments(CustomAttribute attribute, Collection`1 parameters)
     at Mono.Cecil.MetadataReader.ReadCustomAttributeSignature(CustomAttribute attribute)
     at Mono.Cecil.CustomAttribute.<Resolve>b__35_0(CustomAttribute attribute, MetadataReader reader)
     at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
     at Mono.Cecil.CustomAttribute.get_ConstructorArguments()
     at NuGetPackageVerifier.Rules.AssemblyIsBuiltInReleaseConfiguraitonRule.HasReleaseConfiguration(Collection`1 assemblyAttributes)
     at NuGetPackageVerifier.Rules.AssemblyIsBuiltInReleaseConfiguraitonRule.<ValidateAttribute>d__0.MoveNext()
     at NuGetPackageVerifier.Rules.SigningVerificationCompositeRule.<Validate>d__1.MoveNext()
     at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
     at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
     at NuGetPackageVerifier.PackageAnalyzer.AnalyzePackage(PackageAnalysisContext context)
     at NuGetPackageVerifier.Program.Main(String[] args)
\dnx.msbuild(178,9): error MSB3073: The command "dotnet \tools\commands\NuGetPackageVerifier\NuGetPackageVerifier.dll "\artifacts\Signed\Packages\ " "\tools\NuGetPackageVerifier.json"" exited with code 255.
```

**Comment by pranavkm** [comment]
@Eilon - disabling the `AssemblyIsBuiltInReleaseConfiguraitonRule` temporarily until we can get someone to look in to this. It's the only rule that breaks since we converted the verifier from a desktop to a coreclr app.

**Comment by pranavkm** [comment]
https://github.com/aspnet/BuildTools/commit/06d012fc11489f78460efe915685774c87da22cc is the commit to revert once this is sorted.

**Comment by Eilon** [comment]
Moving to preview2.

**Comment by ajaybhargavb** [comment]
a491ebb68848f599e5ae9fc23508b82ca67640b4
