### ISSUE TITLE
API check broken for .NET Core 2.1 targets

### ISSUE THREAD

**Issue by davidfowl** [aspnet/BuildTools#473]
```
  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.1.0, Culture=neutral,                               PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
    System.IO.FileNotFoundException: Could not load the specified file.
    --- End of inner exceptions ---
    --- End of loader exceptions ---
     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
     at System.Reflection.RuntimeAssembly.get_DefinedTypes()
     at ApiCheck.ApiListingGenerator.GenerateApiListing() in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\ApiListingGene                              rator.cs:line 41
     at ApiCheck.Program.OnCompare(CommandLineApplication command, CommandOption apiListingPathOption, CommandOption bre                              akingChangesPathOption, CommandOption assemblyPath, CommandOption assetsJson, CommandOption framework, CommandOption exc                              ludeInternalNamespace) in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 212
     at ApiCheck.Program.<>c__DisplayClass2_1.<Main>b__3() in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:li                              ne 69
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\b\w\9571b3e5f03d051f\s                              hared\Microsoft.Extensions.CommandLineUtils.Sources\CommandLine\CommandLineApplication.cs:line 293
     at ApiCheck.Program.Main(String[] args) in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 81
```

**Comment by javiercn** [comment]
@davidfowl Closing this as this was just about updating the tool and that was done. @ryanbrandenburg in case he ran into this issue and is still active but I highly doubt it.
