### ISSUE TITLE
ApiCheck crashed trying to load types from System.Memory

### ISSUE THREAD

**Issue by pakrym** [aspnet/BuildTools#592]
```
 System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    --- End of loader exceptions ---
  System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.IBufferWriter`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
  Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.IBufferWriter`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    System.TypeLoadException: Could not load type 'System.Buffers.ReadOnlySequence`1' from assembly 'System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
    --- End of loader exceptions ---
     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
     at System.Reflection.RuntimeAssembly.get_DefinedTypes()
     at ApiCheck.ApiListingGenerator.GenerateApiListing() in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\ApiListingGenerator.cs:line 41
     at ApiCheck.Program.OnCompare(CommandLineApplication command, CommandOption apiListingPathOption, CommandOption breakingChangesPathOption, CommandOption assemblyPath, CommandOption assetsJson, CommandOption framework, CommandOption excludeInternalNamespace) in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 212
     at ApiCheck.Program.<>c__DisplayClass2_2.<Main>b__4() in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 69
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\b\w\9571b3e5f03d051f\shared\Microsoft.Extensions.CommandLineUtils.Sources\CommandLine\CommandLineApplication.cs:line 293
     at ApiCheck.Program.Main(String[] args) in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 81
     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
     at System.Reflection.RuntimeAssembly.get_DefinedTypes()
     at ApiCheck.ApiListingGenerator.GenerateApiListing() in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\ApiListingGenerator.cs:line 41
     at ApiCheck.Program.OnCompare(CommandLineApplication command, CommandOption apiListingPathOption, CommandOption breakingChangesPathOption, CommandOption assemblyPath, CommandOption assetsJson, CommandOption framework, CommandOption excludeInternalNamespace) in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 212
     at ApiCheck.Program.<>c__DisplayClass2_2.<Main>b__4() in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 69
     at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args) in C:\b\w\9571b3e5f03d051f\shared\Microsoft.Extensions.CommandLineUtils.Sources\CommandLine\CommandLineApplication.cs:line 293
     at ApiCheck.Program.Main(String[] args) in C:\b\w\9571b3e5f03d051f\src\ApiCheck.Console\Program.cs:line 81
C:\Users\pakrymet\.nuget\packages\internal.aspnetcore.sdk\2.1.0-preview2-15707\build\ApiCheck.targets(39,5): error MSB6006: "dotnet.exe" exited with code 1. [D:\github\aspnet\KestrelHttpServer\src\Kestrel.Transport.Libuv\Kestrel.Transport.Libuv.csproj]
C:\Users\pakrymet\.nuget\packages\internal.aspnetcore.sdk\2.1.0-preview2-15707\build\ApiCheck.targets(39,5): error MSB6006: "dotnet.exe" exited with code 1. [D:\github\aspnet\KestrelHttpServer\src\Kestrel.Core\Kestrel.Core.csproj]
```
/cc @javiercn @natemcmaster  @davidfowl

**Comment by natemcmaster** [comment]
This is most likely due to https://github.com/aspnet/BuildTools/issues/198. We need to rebuild API check whenever there are changes in the runtime as it relies on System.Reflection to load binaries.

**Comment by javiercn** [comment]
Fixed in d944172721e77b6ca05a512303a0859634786746

**Comment by pakrym** [comment]
Happened again during the recent round of updates. I reopened same issues.

**Comment by Eilon** [comment]
In the meantime let's update the version of System.Memory that this tool uses to the latest build. In the future we'll change how this tool works to avoid this problem.

**Comment by javiercn** [comment]
I’ll take care of this tomorrow

**Comment by mkArtakMSFT** [comment]
@javiercn, did you get chance to look into this?

**Comment by javiercn** [comment]
We just need to rebuild the tool.

**Comment by mkArtakMSFT** [comment]
Did this happen already?? Should the be closed?

**Comment by pakrym** [comment]
This is a recurring issue that happens every time we take new versions of corefx with API changes. Rebuilding app helps only untill next time API change happens.

**Comment by natemcmaster** [comment]
_Engineering team triage:_ closing because we are de-prioritizing work on our ApiCheck tool. We plan to convert to a new tool for managing our public API surface. Until this is done, we will fix urgent issues with ApiCheck, but this does not appear to be an urgent item. See https://github.com/aspnet/BuildTools/issues/747
