### ISSUE TITLE
Sdk_CreateSourceLink task fails for Newtonsoft.Json

### ISSUE THREAD

**Issue by smitpatel** [aspnet/BuildTools#659]
```
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: The "Sdk_CreateSourceLink" task failed unexpectedly.
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: File name: 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018:    at Microsoft.AspNetCore.BuildTools.Sdk_CreateSourceLink.Execute()
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: 
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: WRN: Assembly binding logging is turned OFF.
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: Note: There is some performance penalty associated with assembly bind failure logging.
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018: To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
20>%USERPROFILE%\.nuget\packages\internal.aspnetcore.sdk\2.2.0-preview1-17037\build\Git.targets(54,5): warning MSB4018:
```

Building EFCore.Runtime.sln shows above warnings in VS. (EFCore.sln should be the same) 
`Newtonsoft.Json` is being pulled by `Microsoft.Azure.DocumentDB.Core` package which is used in Cosmos SQL provider.
This happens in release/2.1 & dev branch both.
VS Version: 15.8.0 Preview 1.0 [27626.0.d15.8] / 15.6.7 Public release
release/2.1 dotnet SDK version - 2.1.300-preview3-008646
dev dotnet SDK version - 2.1.300-preview2-008530

**Comment by natemcmaster** [comment]
Can you produce a binary log?

Open a VS 2017 Developer Command Prompt 
Navigate to your project
`$ MSBuild.exe EFCore.sln /bl`
Share the msbuild.binlog file

**Comment by smitpatel** [comment]
[msbuild.zip](https://github.com/aspnet/BuildTools/files/1961629/msbuild.zip)

**Comment by natemcmaster** [comment]
The build log doesn't contain the MSB4018 error. Are you able to reproduce this on command-line with msbuild.exe?

**Comment by smitpatel** [comment]
Command line `build /t:Compile` does not produce warning.
I tried MSBuild.exe EFCore.sln but too much output so not sure if it produces warning either.
Build inside VS consistently produces warning.

**Comment by natemcmaster** [comment]
Try `MSBuild.exe EFCore.sln /v:m`

**Comment by smitpatel** [comment]
That did not produce warning either.
